// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xkzpmcnlvmiqqapuqabo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhrenBtY25sdm1pcXFhcHVxYWJvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg3MTcxODEsImV4cCI6MjA2NDI5MzE4MX0.ZmNziwyJn6_5_zmsNsfeTcnAXovcA9FKe0sfDATJRc8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);